import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/Components/Header'
import Hero from '@/Components/Hero'
import { About } from '@/Components/About'
import Skills from '@/Components/Skills'
import { Projects } from '@/Components/Projects'
import { Contact } from '@/Components/Contact'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gradient-to-r from-[#ebbba7] via-[#d299c2] to-[#cfc7f8] overflow-y-scroll overflow-x-hidden z-0 scrollbar  scroll-thumb-[#f5576c] scrollbar-track-[#f5576c]`}>
      <Header/>
      <Hero/>
      <About/>
      <Skills/>
      <Projects/>
      <Contact/>
      {children}</body>
    </html>
  )
}
